trigger:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest

  steps:
  - checkout: self
    clean: true

  - task: PowerShell@2
    displayName: Install dotnet
    inputs:
      arguments:
        version: 7.0.0
      filePath: 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1'

  - task: DotNetCoreCLI@2  
    displayName: Install NBGV tool
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - script: nbgv cloud
    displayName: Set Version

  - task: DotNetCoreCLI@2
    displayName: Build

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      searchPatternPack: '**/*.csproj;!**/*.Tests.csproj'
      outputDir: $(Build.ArtifactStagingDirectory)\Package
      versioningScheme: byBuildNumber

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
